# This workflow will run benchmarks with airspeed velocity (asv) for pull requests.
# It will compare the performance of the main branch with the performance of the merge
# with the new changes and publish a comment with this assessment.

name: Run ASV benchmarks for PR

jobs:
  asv-pr:
    extends:
      template: .github/workflows/asv/asv-template.yml
    permissions:
      actions: read
      pull-requests: write
    steps:
      - name: Get current job logs URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}
      - name: Run comparison of PR against main branch
        run: |
          git remote add upstream https://github.com/${{ github.repository }}.git
          git fetch upstream
          asv continuous upstream/main HEAD --verbose || true
          asv compare upstream/main HEAD --sort ratio --verbose | tee output
          python -m lf_asv_formatter --asv_version "$(echo asv --version)"
          printf "\n\nClick [here]($STEP_URL) to view all benchmarks." >> output
        env:
          STEP_URL: "${{ steps.jobs.outputs.html_url }}#step:8:1"
      - name: Find benchmarks comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: view all benchmarks
      - name: Create or update benchmarks comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: ${{ env.WORKING_DIR }}/output
          edit-mode: replace
