name: airspeed-velocity

env:
  PYTHON_VERSION: "3.10"
  WORKING_DIR: ${{ github.workspace }}/benchmarks

defaults:
  run:
    working-directory: ${{ env.WORKING_DIR }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-asv:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Python ${{ env.PYTHON_VERSION }}
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: python-${{ env.PYTHON_VERSION }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install asv==0.6.1 virtualenv tabulate
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Create ASV machine config file
        run: asv machine --machine gh-runner --yes
      - name: Checkout branch of the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0