# This workflow will run daily at 06:45.
# It will run benchmarks with airspeed velocity (asv)
# and compare performance with the previous nightly build.

name: Run benchmarks nightly job

on:
  schedule:
    - cron: 45 6 * * *
  workflow_dispatch:

jobs:
  asv-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/asv/asv-nightly.yml